live_config_reload=true

import = [
  "~/alacritty-catppucin/catppuccin-mocha.toml"
]

[scrolling]
history = 10000
multiplier = 3

[env]
TERM = "xterm-256color"

[window]
dynamic_padding=true
padding.x = 8 
padding.y =8

decorations = "Buttonless"
class.instance = "Alacritty"
class.general = "Alacritty"
option_as_alt = "Both"

[font]
  normal.family="FiraMono Nerd Font"
  size = 16

[keyboard]

bindings = [
{key="Space", mods="Control", action = "ToggleFullScreen" }
]
